return {}
-- return {
--     'Wansmer/langmapper.nvim',
--     lazy = false,
--     priority = 1,
--     opts = {},
--     init = function()
--         local ru = [['йцукенгшщзхїґфівапролджєячсмитьбю.]]
--         local RU = [[ʼЙЦУКЕНГШЩЗХЇҐФІВАПРОЛДЖЄЯЧСМИТЬБЮ,]]
--         local en = [[`qwfpgjluy;[]\arstdhneio'zxcvbkm,./]]
--         local EN = [[~QWFPGJLUY:{}|ARSTDHNEIO"ZXCVBKM<>?]]
--
--         local function escape(str)
--             local escape_chars = [[;,."|\]]
--             return vim.fn.escape(str, escape_chars)
--         end
--
--         vim.opt.langmap = vim.fn.join({
--             escape(RU) .. ';' .. escape(EN),
--             escape(ru) .. ';' .. escape(en),
--         }, ',')
--     end
-- }
